default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # Config from docker-compose, needs to be set by your own database
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: rails_7_features_development

test:
  <<: *default
  database: rails_7_features_test

production:
  <<: *default
  database: rails_7_features_production
  username: rails_7_features
  password: <%= ENV["RAILS_7_FEATURES_DATABASE_PASSWORD"] %>
